/**
 * Endpoint registry — machine-readable map of every REST endpoint this SDK
 * implements, the single source of truth consumed by:
 *
 *  - `docs/endpoint-map/*.md` (generated by scripts/generate-endpoint-map.ts)
 *  - `llms.txt` / `llms-full.txt` (agent-facing docs, also generated)
 *  - tooling/CI (coverage accounting vs. Binance's published API surface)
 *
 * Registry entries are hand-curated but mechanically *checked*: the
 * `scripts/generate-endpoint-map.ts` script greps `src/resources` for live
 * `http.<verb>(...)` calls and fails when a registered endpoint is not
 * actually implemented (or vice versa), so the map cannot drift silently.
 */

export type EndpointAuth = 'public' | 'apiKey' | 'signed';
export type EndpointMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';

export interface EndpointEntry {
  /** Binance product family. */
  product: 'spot' | 'usdm' | 'coinm' | 'margin' | 'wallet' | 'subaccount';
  /** SDK surface implementing it, e.g. `futures.trading.createOrder`. */
  operation: string;
  method: EndpointMethod;
  path: string;
  authentication: EndpointAuth;
  /** Documented request weight where known (IP weight unless noted). */
  weight?: number;
  /** Resource class + method implementing the call. */
  implementedBy: string;
}

import { SPOT_ENDPOINTS } from './spot.endpoints.js';
import { USDM_ENDPOINTS } from './usdm.endpoints.js';
import { COINM_ENDPOINTS } from './coinm.endpoints.js';
import { MARGIN_ENDPOINTS } from './margin.endpoints.js';
import { WALLET_ENDPOINTS } from './wallet.endpoints.js';
import { SUBACCOUNT_ENDPOINTS } from './subaccount.endpoints.js';

/** Every implemented endpoint, across all products. */
export const ENDPOINT_REGISTRY: readonly EndpointEntry[] = [
  ...SPOT_ENDPOINTS,
  ...USDM_ENDPOINTS,
  ...COINM_ENDPOINTS,
  ...MARGIN_ENDPOINTS,
  ...WALLET_ENDPOINTS,
  ...SUBACCOUNT_ENDPOINTS,
];

export interface EndpointQuery {
  product?: EndpointEntry['product'];
  method?: EndpointMethod;
  authentication?: EndpointAuth;
  pathPrefix?: string;
}

export function listEndpoints(query: EndpointQuery = {}): readonly EndpointEntry[] {
  return ENDPOINT_REGISTRY.filter((entry) => {
    if (query.product && entry.product !== query.product) return false;
    if (query.method && entry.method !== query.method) return false;
    if (query.authentication && entry.authentication !== query.authentication) return false;
    if (query.pathPrefix && !entry.path.startsWith(query.pathPrefix)) return false;
    return true;
  });
}

export function findEndpoint(path: string, method?: EndpointMethod): EndpointEntry | undefined {
  return ENDPOINT_REGISTRY.find(
    (entry) => entry.path === path && (method === undefined || entry.method === method),
  );
}

/** Per-product coverage counts for docs/CI. */
export function endpointCounts(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const entry of ENDPOINT_REGISTRY) {
    counts[entry.product] = (counts[entry.product] ?? 0) + 1;
  }
  return counts;
}
